"""Tests for the grammar renderer."""

from __future__ import annotations

import re

import pytest

from cve2grammar.generalizer.render import render_grammar


def _ok_entry(**overrides) -> dict:
    entry = {
        "bug_id": "MR-SQLITE-0001",
        "status": "ok",
        "template": "SELECT * FROM {Table-Name}",
        "feature_tag": "basic_select",
        "weight": 3.0,
        "notes": "",
    }
    entry.update(overrides)
    return entry


def _fallback_entry(**overrides) -> dict:
    entry = _ok_entry(status="fallback", template="SELECT literal FROM t")
    entry.update(overrides)
    return entry


class TestEmpty:
    def test_empty_list_still_produces_header(self) -> None:
        out = render_grammar([])
        assert "# Auto-generated by cve2grammar/generalizer" in out
        assert "ctx.rule" not in out


class TestSingleEntry:
    def test_single_ok_entry_emits_one_rule(self) -> None:
        out = render_grammar([_ok_entry(bug_id="MR-SQLITE-0001")])
        assert out.count("ctx.rule(") == 1
        assert "SELECT * FROM {Table-Name}" in out
        assert "weight=3.0" in out
        assert "MR-SQLITE-0001" in out

    def test_single_rule_has_feature_tag_comment(self) -> None:
        out = render_grammar([_ok_entry(feature_tag="basic_select")])
        assert "basic_select" in out


class TestGrouping:
    def test_same_feature_tag_collapses_to_one_rule(self) -> None:
        entries = [
            _ok_entry(bug_id="MR-SQLITE-0001", feature_tag="collate_nocase"),
            _ok_entry(bug_id="MR-SQLITE-0014", feature_tag="collate_nocase"),
        ]
        out = render_grammar(entries)
        assert out.count("ctx.rule(") == 1
        assert "MR-SQLITE-0001" in out
        assert "MR-SQLITE-0014" in out

    def test_different_feature_tags_emit_separate_rules(self) -> None:
        entries = [
            _ok_entry(bug_id="A", feature_tag="tag_a"),
            _ok_entry(bug_id="B", feature_tag="tag_b"),
        ]
        out = render_grammar(entries)
        assert out.count("ctx.rule(") == 2


class TestOrdering:
    def test_groups_sorted_alphabetically_by_feature_tag(self) -> None:
        entries = [
            _ok_entry(bug_id="Z", feature_tag="zulu"),
            _ok_entry(bug_id="A", feature_tag="alpha"),
            _ok_entry(bug_id="M", feature_tag="mike"),
        ]
        out = render_grammar(entries)
        idx_alpha = out.index("alpha")
        idx_mike = out.index("mike")
        idx_zulu = out.index("zulu")
        assert idx_alpha < idx_mike < idx_zulu

    def test_bug_ids_within_group_sorted_lex(self) -> None:
        entries = [
            _ok_entry(bug_id="MR-SQLITE-0099", feature_tag="x"),
            _ok_entry(bug_id="MR-SQLITE-0001", feature_tag="x"),
            _ok_entry(bug_id="MR-SQLITE-0042", feature_tag="x"),
        ]
        out = render_grammar(entries)
        ids_in_comment = re.findall(r"MR-SQLITE-\d{4}", out)
        assert ids_in_comment == ["MR-SQLITE-0001", "MR-SQLITE-0042", "MR-SQLITE-0099"]


class TestFallback:
    def test_fallback_entries_appear_at_bottom(self) -> None:
        entries = [
            _ok_entry(bug_id="A", feature_tag="good"),
            _fallback_entry(bug_id="B"),
        ]
        out = render_grammar(entries)
        idx_good = out.index("good")
        idx_fallback_header = out.index("FALLBACK")
        assert idx_good < idx_fallback_header

    def test_fallback_rule_has_fallback_comment_prefix(self) -> None:
        entries = [_fallback_entry(bug_id="MR-SQLITE-0042")]
        out = render_grammar(entries)
        assert "# FALLBACK:" in out
        assert "MR-SQLITE-0042" in out

    def test_fallback_entries_do_not_merge_with_ok_group(self) -> None:
        entries = [
            _ok_entry(bug_id="A", feature_tag="shared"),
            _fallback_entry(bug_id="B", feature_tag="shared"),
        ]
        out = render_grammar(entries)
        # Two rule emissions — one OK, one fallback
        assert out.count("ctx.rule(") == 2


class TestHeader:
    def test_header_contains_timestamp_and_count(self) -> None:
        entries = [_ok_entry(bug_id="A"), _ok_entry(bug_id="B")]
        out = render_grammar(entries)
        assert re.search(r"\d{4}-\d{2}-\d{2}", out)
        assert "Bugs: 2" in out

    def test_header_mentions_prompt_version(self) -> None:
        out = render_grammar([])
        assert "Prompt version:" in out
