"""Render accumulator entries to a Nautilus-compatible grammar source file.

Two deterministic sections, in this order:

1. OK group: entries with ``status == "ok"``. Grouped by ``feature_tag``;
   each group becomes one ``ctx.rule`` call with a comment enumerating
   the contributing bug ids. Groups sorted alphabetically by tag.
2. Fallback block: entries with ``status == "fallback"``, each emitted
   individually with a ``# FALLBACK:`` comment and the literal original
   SQL as the template. Sorted by bug id.

Determinism matters because the renderer's output is committed to git
(indirectly — through the cache) and expected to be byte-reproducible
from a given cache snapshot.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from cve2grammar.generalizer import PROMPT_VERSION


def render_grammar(entries: list[dict]) -> str:
    """Return the full source of ``generated/sqlite_grammar_v2.py``.

    Args:
        entries: Accumulated cache payloads. Each entry has at minimum:
            ``bug_id``, ``status`` (``"ok"`` or ``"fallback"``),
            ``template``, ``feature_tag``, ``weight``, ``notes``.

    Returns:
        Complete Python source as a single string, ending in ``\\n``.
    """
    parts: list[str] = [_header(entries)]
    parts.append(_render_ok_groups(entries))
    parts.append(_render_fallbacks(entries))
    return "".join(parts)


def _header(entries: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    models = sorted({e.get("model", "unknown") for e in entries}) or ["unknown"]
    return (
        "# Auto-generated by cve2grammar/generalizer — do not edit by hand.\n"
        f"# Generated: {now}\n"
        f"# Model: {', '.join(models)}\n"
        f"# Prompt version: {PROMPT_VERSION}\n"
        f"# Bugs: {len(entries)} (crash oracle)\n"
        "# Source: cve2grammar generalize-candidates --oracle crash\n"
        "\n"
    )


def _render_ok_groups(entries: list[dict]) -> str:
    ok = [e for e in entries if e.get("status") == "ok"]
    if not ok:
        return ""
    groups: dict[str, list[dict]] = {}
    for e in ok:
        groups.setdefault(e["feature_tag"], []).append(e)

    out: list[str] = []
    for tag in sorted(groups):
        bugs = sorted(groups[tag], key=lambda e: e["bug_id"])
        bug_ids = [b["bug_id"] for b in bugs]
        canonical = bugs[0]
        plural = "s" if len(bugs) > 1 else ""
        comment = f"# === {tag} ({len(bugs)} bug{plural}: {', '.join(bug_ids)}) ==="
        out.append(comment + "\n")
        out.append(_emit_rule(canonical))
        out.append("\n")
    return "".join(out)


def _render_fallbacks(entries: list[dict]) -> str:
    fb = sorted(
        (e for e in entries if e.get("status") == "fallback"),
        key=lambda e: e["bug_id"],
    )
    if not fb:
        return ""
    out: list[str] = [
        "# ============================================================\n",
        "# FALLBACKS — templates that failed validation; literal SQL kept.\n",
        "# ============================================================\n\n",
    ]
    for entry in fb:
        out.append(f"# FALLBACK: {entry['bug_id']} — {entry.get('notes', '')}\n")
        out.append(_emit_rule(entry))
        out.append("\n")
    return "".join(out)


def _emit_rule(entry: dict) -> str:
    """Format one ``ctx.rule("Sql-Stmt", ..., weight=...)`` call."""
    template = entry["template"]
    weight = entry["weight"]
    lines = template.split("\n")
    if len(lines) == 1:
        body = _py_literal(lines[0])
        return f'ctx.rule("Sql-Stmt", {body}, weight={weight})\n'
    fragments = [_py_literal(line + ("\n" if i < len(lines) - 1 else "")) for i, line in enumerate(lines)]
    indented = "\n    ".join(fragments)
    return f'ctx.rule("Sql-Stmt",\n    {indented},\n    weight={weight})\n'


def _py_literal(s: str) -> str:
    """Emit a Python double-quoted string literal with backslash+quote escaping."""
    escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def main(argv: list[str] | None = None) -> int:
    """CLI entry point. Reads accumulator JSON from stdin, writes the grammar file.

    Usage:
        python3 -m cve2grammar.generalizer.render <output_path>

    Exit codes:
        0 — success, file written
        2 — malformed JSON on stdin, or missing output path argument
    """
    args = list(argv) if argv is not None else sys.argv[1:]
    if not args:
        print(
            "usage: python3 -m cve2grammar.generalizer.render <output_path>",
            file=sys.stderr,
        )
        return 2
    output = Path(args[0])

    raw = sys.stdin.read()
    try:
        entries = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"malformed json on stdin: {e}", file=sys.stderr)
        return 2

    source = render_grammar(entries)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(source, encoding="utf-8")

    total = len(entries)
    fallbacks = sum(1 for e in entries if e.get("status") == "fallback")
    print(f"Wrote {output} — {total} bugs, {fallbacks} fallbacks.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
